## Fake News Classifier Using LSTM

Dataset: https://www.kaggle.com/c/fake-news/data#

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('train.csv')

In [3]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [36]:
df.shape

(20800, 5)

In [37]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [38]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [39]:
###Drop Nan Values
df=df.dropna()


In [40]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [41]:
df.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [42]:
## Get the Independent Features

X=df.drop('label',axis=1)

In [43]:
## Get the Dependent features
y=df['label']

In [44]:
X.shape

(18285, 4)

In [45]:
y.shape

(18285,)

In [46]:
import tensorflow as tf

In [47]:
tf.__version__

'2.15.0'

In [48]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [49]:
### Vocabulary size
voc_size=5000

### Onehot Representation

In [50]:
messages=X.copy()

In [51]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [52]:
messages

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [53]:
#messages.reset_index(inplace=True)

In [54]:
messages

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [55]:
import nltk
import re
from nltk.corpus import stopwords

In [56]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [59]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
  # Access the title using the iloc indexer to avoid potential index issues
  review = re.sub('[^a-zA-Z]', ' ', messages['title'].iloc[i])
  review = review.lower()
  review = review.split()

  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

In [60]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [61]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [64]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [65]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[243, 3077, 4715, 2489, 3213, 4207, 3283, 3568, 85, 2506],
 [1623, 3558, 2930, 2082, 2843, 3737, 2290],
 [1766, 1655, 1424, 2020],
 [3139, 2473, 4828, 283, 3286, 67],
 [380, 2843, 966, 1297, 4566, 2588, 2843, 1638, 3482, 752],
 [1145,
  4075,
  828,
  3725,
  4442,
  3378,
  4461,
  162,
  2174,
  2357,
  2365,
  2653,
  116,
  4252,
  2290],
 [3627, 3256, 741, 638, 1481, 4955, 1274, 3220, 4047, 972, 1226],
 [734, 371, 601, 4660, 3546, 3217, 3378, 2975, 4047, 972, 1226],
 [3558, 4811, 572, 1034, 2992, 3390, 2154, 305, 3378, 1569],
 [2657, 1269, 2924, 1712, 3371, 4412, 3975, 1770],
 [2726, 3540, 4215, 307, 886, 3234, 806, 202, 616, 2090, 4615],
 [283, 387, 3213, 3390, 3378, 3546],
 [1786, 106, 598, 4807, 4814, 2731, 1800, 1222, 3195],
 [1192, 536, 200, 4100, 3881, 165, 1998, 4047, 972, 1226],
 [877, 4966, 330, 2641, 269, 4047, 972, 1226],
 [3521, 4394, 4719, 1741, 2041, 4089, 3234, 1402, 4654, 1490],
 [1948, 1285, 3558],
 [434, 2078, 2000, 2455, 3378, 1537, 585, 2290],
 [2779, 2114, 29

In [66]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [67]:
onehot_repr[1]

[1623, 3558, 2930, 2082, 2843, 3737, 2290]

### Embedding Representation

In [79]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[ 243 3077 4715 ...    0    0    0]
 [1623 3558 2930 ...    0    0    0]
 [1766 1655 1424 ...    0    0    0]
 ...
 [ 292 2768 1726 ...    0    0    0]
 [4727 3546   44 ...    0    0    0]
 [ 288  369 4252 ...    0    0    0]]


In [80]:
embedded_docs[1]

array([1623, 3558, 2930, 2082, 2843, 3737, 2290,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [81]:
embedded_docs[0]

array([ 243, 3077, 4715, 2489, 3213, 4207, 3283, 3568,   85, 2506,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [82]:
## Creating model
embedding_vector_features=40 ##features representation
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 20, 40)            200000    
                                                                 
 lstm_2 (LSTM)               (None, 100)               56400     
                                                                 
 dense_2 (Dense)             (None, 1)                 101       
                                                                 
Total params: 256501 (1001.96 KB)
Trainable params: 256501 (1001.96 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [83]:
len(embedded_docs),y.shape

(18285, (18285,))

In [84]:
embedded_docs.shape

(18285, 20)

In [85]:
type(embedded_docs)

numpy.ndarray

In [86]:
import numpy as np
X_final=np.array(embedded_docs)#convert list into array
y_final=np.array(y)

In [87]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [88]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

### Model Training

In [89]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 16s 65ms/step - loss: 0.3046 - accuracy: 0.8544 - val_loss: 0.2009 - val_accuracy: 0.9178
Epoch 2/10
192/192 [==============================] - 3s 18ms/step - loss: 0.1323 - accuracy: 0.9521 - val_loss: 0.2117 - val_accuracy: 0.9221
Epoch 3/10
192/192 [==============================] - 4s 21ms/step - loss: 0.0817 - accuracy: 0.9710 - val_loss: 0.2233 - val_accuracy: 0.9130
Epoch 4/10
192/192 [==============================] - 2s 12ms/step - loss: 0.0568 - accuracy: 0.9808 - val_loss: 0.2920 - val_accuracy: 0.9160
Epoch 5/10
192/192 [==============================] - 2s 10ms/step - loss: 0.0397 - accuracy: 0.9866 - val_loss: 0.3347 - val_accuracy: 0.9047
Epoch 6/10
192/192 [==============================] - 2s 10ms/step - loss: 0.0271 - accuracy: 0.9913 - val_loss: 0.4000 - val_accuracy: 0.9084
Epoch 7/10
192/192 [==============================] - 2s 10ms/step - loss: 0.0223 - accuracy: 0.9927 - val_loss: 0.4230 - val_accuracy: 0.911

### Adding Dropout

In [90]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

### Performance Metrics And Accuracy

In [91]:
y_pred=model.predict(X_test)

189/189 [==============================] - 1s 2ms/step


In [92]:
y_pred=np.where(y_pred > 0.6, 1,0) ##AUC ROC Curve

In [93]:
from sklearn.metrics import confusion_matrix

In [94]:
confusion_matrix(y_test,y_pred)

array([[3419,    0],
       [2616,    0]])

In [95]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.5665285832642917

In [96]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.57      1.00      0.72      3419
           1       0.00      0.00      0.00      2616

    accuracy                           0.57      6035
   macro avg       0.28      0.50      0.36      6035
weighted avg       0.32      0.57      0.41      6035



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
